#!/bin/sh

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -ex

if [ -z $GITHUB_ACTIONS ]; then
    scripts/check
fi
export COVERAGE_CORE=sysmon

${PREFIX}coverage run -m pytest --verbose "$@"

if [ -z $GITHUB_ACTIONS ]; then
    scripts/coverage
fi
